---
- hosts: backend
  vars:
    backend: /home/raduga/raduga-server
    upload_folder: /home/raduga/photos/

  tasks:

  - name: Install required packages
    apt: pkg={{ item }} state=installed update_cache=yes
    with_items:
    - python3
    - python3-dev
    - virtualenvwrapper
    - git
    - build-essential
    - mongodb
    - libjpeg-dev
    - libjpeg8-dev
    - libpng3 
    - libfreetype6-dev
    - zlib1g-dev
    - openjdk-7-jre-headless
    - imagemagick
    - potrace
    - supervisor
    - nginx
    - postgresql-9.3
    - postgresql-9.3-postgis-2.1
    - postgresql-server-dev-9.3
    - python-psycopg2

  - name: Create upload folder
    file: path={{ upload_folder }} state=directory owner=www-data group=www-data mode=0755
    
  - name: Set Time Zone
    copy: src=files/timezone dest=/etc/timezone owner=root group=root mode=0644 
    notify:
      - update timezone

  - name: Copy server environment
    copy: src=files/environment dest=/etc

  - name: Create raduga user
    user: name=raduga comment="Raduga Backend user account"

  - authorized_key: user=raduga key="{{ lookup('file', '/home/arjan/.ssh/id_rsa.pub') }}"

  - name: Checkout the backend repo
    git: repo=https://github.com/arjan/raduga-server.git dest={{ backend }} version=master accept_hostkey=True
    sudo: yes
    sudo_user: raduga
    notify: update supervisor

  - name: Manually create the initial virtualenv
    command: virtualenv /home/raduga/venv -p python3.4 creates="/home/raduga/venv"
    sudo: yes
    sudo_user: raduga

  - name: Install python dependencies
    pip: 
      requirements=/home/raduga/raduga-server/requirements.txt 
      virtualenv=/home/raduga/venv
    sudo: yes
    sudo_user: raduga

  - name: Add local_settings.py
    copy: src=files/local_settings.py dest={{ backend }}/local_settings.py
    sudo: yes
    sudo_user: raduga

  - name: Add grib2json
    unarchive: src=files/grib2json-0.8.0-SNAPSHOT.tar.gz dest=/home/raduga creates="/home/raduga/grib2json-0.8.0-SNAPSHOT"
    sudo: yes
    sudo_user: raduga

  - name: Add predict.sh crontab
    cron: name=predict minute="30" job="echo 'source /home/raduga/venv/bin/activate; {{ backend }}/predict.sh' | /bin/bash"
    sudo: yes
    sudo_user: raduga

  - name: Add cleanup.sh crontab
    cron: name=cleanup minute="0" job="{{ backend }}/cleanup.sh"
    sudo: yes
    sudo_user: raduga

  - name: Install supervisor job
    copy: src=files/server.conf dest=/etc/supervisor/conf.d/
    notify: update supervisor

  - name: Install nginx vhost
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-enabled/01raduga
    notify: reload nginx

  - name: Check if dbs are created already
    shell: "psql -c 'select 1'"
    sudo: yes
    sudo_user: postgres
    register: db_setup
    ignore_errors: yes

  - name: Setup postgres cluster to default to utf8
    shell: "pg_createcluster --start -e UTF-8 9.3 main"
    when: db_setup.rc != 0 # only do this if the dbs haven't been created yet
 
  - name: Install postgres user
    sudo: yes
    sudo_user: postgres
    postgresql_user: name=raduga password=raduga

  - name: Install main database
    sudo: yes
    sudo_user: postgres
    postgresql_db: name=raduga owner=raduga
     
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata

    - name: update supervisor
      supervisorctl: name=raduga-server state=restarted

    - name: reload nginx
      service: name=nginx state=restarted
